name: Build Docker Image with Kaniko

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: my-app
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: 
  DOCKER_PASSWORD: 
  
jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker configuration
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"${{ env.DOCKER_REGISTRY }}\":{\"username\":\"${{ env.DOCKER_USERNAME }}\",\"password\":\"${{ env.DOCKER_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          builder: gcr.io/kaniko-project/executor:latest
